site_name: OSchengdu_page
site_url: https://OSchengdu.github.io/mkdocs-page/
nav:
    - main: 
      - introduction: index.md
      - related link: project/group.md
      - contact us: project/contact.md
      - about us: about.md
    - project:
        - OSchengdu Website: project/website.md
        - Pure Nasm OS: project/pure_nasm_os.md
    - contributor: project/contributor.md

theme:
    name: material
    palette:
        primary: black
        accent: red
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.instant
        - search.highlight
        - search.share
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - header.autohide
        - footer.follow
        - footer.meta
        - footer.edit
        - footer.license
        - footer.copyright
        - footer.social
        - footer.navigation
        - footer.top
        - footer.bottom
        - footer.divider
        - footer.separator
        - footer.spacer
        - footer.divider
